// Blog posts — ported verbatim. First entry renders as the featured post;
// the rest render as Card Folder (notch + fold-open) accordion cards.
const blogPosts = [
  {
    slug: 'serengeti-timing',
    tag: 'Planning',
    title: 'When Is the Best Time for a Safari in Tanzania?',
    grad: ['#7a6a2f', '#241d0e'],
    readTime: '5 min read',
    excerpt: 'One month gives you rivers full of crocodiles and crossing wildebeest. Another gives you 8,000 calves born a day. Pick the wrong one and you get neither.',
    full: 'The dry season (June–October) concentrates wildlife around shrinking water sources and delivers the Mara River crossings. The short rains in November turn the plains green and quiet. Calving season (January–March) trades crossings for something rawer: birth and predation, side by side, every single day on the Ndutu plains.',
    url: 'https://platoon-tours.com/when-is-the-best-time-for-a-safari-in-tanzania/',
  },
  {
    slug: 'northern-southern-circuit',
    tag: 'Circuits',
    title: 'Northern vs. Southern Circuit: Which Tanzania Safari Fits You',
    grad: ['#3d5c42', '#12201a'],
    readTime: '6 min read',
    excerpt: 'Same country, two completely different safaris. One has the fame and the crowds. The other has wild dogs, empty plains, and nobody else in sight.',
    full: 'The Northern Circuit is efficient, scenic, and built for first-time visitors who want the icons: Serengeti, Ngorongoro, the migration. The Southern Circuit trades convenience for depth — Nyerere and Ruaha reward travelers willing to fly further for a park that feels genuinely undiscovered.',
  },
  {
    slug: 'ndutu-calving',
    tag: 'Wildlife',
    title: 'Inside the Ndutu Calving Season',
    grad: ['#3a5a6e', '#12242c'],
    readTime: '4 min read',
    excerpt: 'A calf hits the ground every few seconds. A lion is already watching. Three months, one plain, and the rawest wildlife spectacle in Africa.',
    full: 'Predators don’t wait for the migration to move — they follow the herds straight onto the plains, and the open, short grass here means you see everything unfold in the open, not through a screen of bush.',
  },
  {
    slug: 'packing-list',
    tag: 'Packing',
    title: 'Tanzania Safari Packing List',
    grad: ['#5c3d2f', '#1e130e'],
    readTime: '3 min read',
    excerpt: 'Half of what’s on the internet’s "ultimate" packing list is dead weight. Here’s the short list our own guides actually tell first-timers to bring.',
    full: 'No safari-branded gear required. What matters is layers for cold mornings, neutral colors that don’t stand out to wildlife, and a bag that packs down small enough for a light-aircraft transfer between camps.',
    url: 'https://platoon-tours.com/tanzania-safaris-parking-list/',
  },
  {
    slug: 'solo-travel',
    tag: 'Solo Travel',
    title: 'Solo Female Travel in Tanzania: What You Actually Need to Know',
    grad: ['#6e3550', '#2a1420'],
    readTime: '5 min read',
    excerpt: 'Traveling alone raises real questions. We answer the ones that matter and skip the ones that only exist online.',
    full: 'Vehicles, guides, and camps are the same regardless of who’s booking — the real differences are ones any solo traveler navigates anywhere: trusting your operator, and knowing exactly who’s picking you up at the airstrip.',
  },
  {
    slug: 'tarangire-secret',
    tag: 'Hidden Gems',
    title: "Tarangire: Tanzania's Best-Kept Secret",
    grad: ['#6e5a35', '#241d0e'],
    readTime: '4 min read',
    excerpt: 'Elephants by the hundreds, baobabs older than the country itself, and a fraction of the vehicles you’ll fight for a view in the Serengeti.',
    full: 'The Tarangire River is the draw in dry season, when elephant herds numbering in the hundreds converge on its banks — a sight that rivals anything in the more famous parks, minus the traffic jam of vehicles.',
  },
  {
    slug: 'park-rules',
    tag: 'Park Rules',
    title: 'What Are the Tanzania National Parks Rules?',
    grad: ['#4a4a4a', '#161616'],
    readTime: '4 min read',
    excerpt: 'From vehicle speed limits to why you never step outside during a game drive — the rules every park enforces, and why they exist.',
    full: 'Rules like staying in the vehicle and respecting speed limits aren’t bureaucracy for its own sake — they’re what keeps the wildlife acting like wildlife, not performers used to being approached.',
    url: 'https://platoon-tours.com/what-are-the-tanzania-national-parks-rules/',
  },
  {
    slug: 'safari-cost',
    tag: 'Budgeting',
    title: 'How Much Does a Tanzania Safari Really Cost?',
    grad: ['#4a4a4a', '#161616'],
    readTime: '6 min read',
    excerpt: 'Two travelers, same parks, ten days apart in price. We break down exactly where that gap comes from — and where it’s worth paying for.',
    full: 'Camping safaris cut cost by trading permanent lodges for mobile tented camps; luxury safaris add private guides, premium lodges, and often light-aircraft transfers instead of long road days. Neither is the "right" choice — it depends what you’re optimizing for.',
  },
  {
    slug: 'zanzibar-extension',
    tag: 'Zanzibar',
    title: 'Zanzibar After the Bush: Planning the Perfect Beach Extension',
    grad: ['#3a5a6e', '#12242c'],
    readTime: '4 min read',
    excerpt: 'Dust to white sand in one flight. Here’s how to time it so the transition feels like a reward, not a rushed afterthought.',
    full: 'Most itineraries fly straight from the Serengeti or Arusha into Zanzibar in under two hours — meaning your last game drive and your first beach sunset can happen on the very same day.',
  },
  {
    slug: 'kilimanjaro-climb',
    tag: 'Kilimanjaro',
    title: 'Climbing Kilimanjaro Without Technical Experience',
    grad: ['#4a4a4a', '#161616'],
    readTime: '7 min read',
    excerpt: 'No ropes, no climbing gear, no experience required — just altitude, willpower, and one very long final night. Here’s what it actually takes.',
    full: 'The Machame route takes six to seven days, gaining altitude slowly enough for most reasonably fit travelers to acclimatize — the real test isn’t technical skill, it’s patience and a willingness to walk slowly.',
  },
  {
    slug: 'kilimanjaro-packing',
    tag: 'Packing',
    title: 'Kilimanjaro Climbing Packing List',
    grad: ['#3d5c56', '#12201e'],
    readTime: '4 min read',
    excerpt: 'It’s summer at the gate and winter at the summit. Pack for one mountain, four climates, and the items climbers always wish they hadn’t skipped.',
    full: 'You’ll sweat through the rainforest zone on day one and need a sub-zero-rated sleeping bag by summit night — pack for four climates, not one mountain.',
    url: 'https://platoon-tours.com/kilimanjaro-climbing-packing-list/',
  },
];

export default blogPosts;
