// Safaris page grid data — feeds components/safaris/TourGrid.jsx +
// TourCard.jsx. `grad` is the two-stop gradient used as cover-art placeholder
// until real photography is in. `url` is the old external platoon-tours.com
// page for this package, kept only as a stray reference — every card now
// links via `slug` to its own /safaris/[slug] detail page instead.
const safariPackages = [
  { title: 'Balloon Safari: 7-Day Luxury Tanzania Safari in the Serengeti', price: 'From $3,700 USD*', special: true, grad: ['#8a6a2f', '#241d0e'], url: 'https://platoon-tours.com/7-day-luxury-tanzania-safari-with-serengeti-balloon-safari/', slug: '7-day-luxury-tanzania-safari-with-serengeti-balloon-safari' },
  { title: '6-Day Tanzania Safari + 5-Day Zanzibar Luxury Escape', price: 'From $3,400 USD*', special: true, grad: ['#3a5a6e', '#12242c'], url: 'https://platoon-tours.com/6-day-tanzania-safari-5-day-zanzibar-luxury-escape/', slug: '6-day-tanzania-safari-5-day-zanzibar-luxury-escape' },
  { title: "5-Day Luxury Honeymoon Safari: Tanzania's Northern Circuit", price: 'From $2,400 USD*', special: true, grad: ['#6e3550', '#2a1420'], url: 'https://platoon-tours.com/5-day-luxury-honeymoon-safari-tanzanias-northern-circuit/', slug: '5-day-luxury-honeymoon-safari-tanzanias-northern-circuit' },
  { title: '6-Day Mid-Range Safari: The Great Calving Season', price: 'From $2,800 USD*', special: true, grad: ['#3d5c42', '#12201a'], url: 'https://platoon-tours.com/6-day-calving-season-safari-ndutu/', slug: '6-day-mid-range-safari-the-great-calving-season' },
  { title: '9-Day Safari: The Ultimate Mara River Crossing Experience', price: 'From $2,500 USD*', special: true, grad: ['#3a5a6e', '#12242c'], url: 'https://platoon-tours.com/9-day-mara-river-crossing-safari/', slug: '9-day-safari-the-ultimate-mara-river-crossing-experience' },
  { title: '9-Day Tanzania Safari Express: Lake Manyara, Lake Natron, Serengeti, Ngorongoro & Tarangire', price: 'From $3,600 USD*', special: false, grad: ['#6e3550', '#2a1420'], url: 'https://platoon-tours.com/9-day-tanzania-safari-express-lake-manyara-lake-natron-serengeti-ngorongoro-tarangire/', slug: '9-day-tanzania-safari-express-lake-manyara-lake-natron-serengeti-ngorongoro-tarangire' },
  { title: '7-Day Wild South Safari: Nyerere & Ruaha', price: 'From $4,600 USD*', special: false, grad: ['#3d5c42', '#12201a'], url: '', slug: '7-day-wild-south-safari-nyerere-ruaha' },
  { title: '8-Day Tanzania Safari Express: Arusha National Park, Lake Manyara, Serengeti, Ngorongoro & Tarangire', price: 'From $2,600 USD*', special: false, grad: ['#6e5a35', '#241d0e'], url: 'https://platoon-tours.com/8-day-tanzania-safari-express-arusha-national-park-lake-manyara-serengeti-ngorongoro-tarangire/', slug: '8-day-tanzania-safari-express-arusha-national-park-lake-manyara-serengeti-ngorongoro-tarangire' },
  { title: '7-Day Tanzania Safari Express: Lake Manyara, Serengeti, Ngorongoro & Tarangire', price: 'From $2,200 USD*', special: false, grad: ['#4a4a4a', '#161616'], url: 'https://platoon-tours.com/7-day-tanzania-safari-express-lake-manyara-serengeti-ngorongoro-tarangire/', slug: '7-day-express-lake-manyara-serengeti-ngorongoro-tarangire' },
  { title: '7-Day Southern Tanzania Safari: Nyerere, Mikumi & Udzungwa', price: 'From $3,700 USD*', special: false, grad: ['#6e5a35', '#241d0e'], url: '', slug: '7-day-southern-tanzania-safari-nyerere-mikumi-udzungwa' },
  { title: '8-Day Tanzania Safari: Western Serengeti & Ngorongoro Crater', price: 'From $2,900 USD*', special: false, grad: ['#4a4a4a', '#161616'], url: 'https://platoon-tours.com/8-day-tanzania-safari-western-serengeti-ngorongoro-crater/', slug: '8-day-tanzania-safari-western-serengeti-ngorongoro-crater' },
  { title: '4-Day Tanzania Safari Express: Lake Manyara, Ngorongoro & Tarangire', price: 'From $1,350 USD*', special: false, grad: ['#5c3d2f', '#1e130e'], url: 'https://platoon-tours.com/4-day-tanzania-safari-express-lake-manyara-ngorongoro-tarangire/', slug: '4-day-express-lake-manyara-ngorongoro-tarangire' },
  { title: '3-Day Tanzania Safari Express: Tarangire & Ngorongoro Crater', price: 'From $1,100 USD*', special: false, grad: ['#5c3d2f', '#1e130e'], url: 'https://platoon-tours.com/3-day-tanzania-safari-express-tarangire-ngorongoro-crater/', slug: '3-day-express-tarangire-ngorongoro' },
  { title: '2-Day Tanzania Safari Express: Tarangire & Ngorongoro Crater', price: 'From $900 USD*', special: false, grad: ['#3d5c56', '#12201e'], url: 'https://platoon-tours.com/2-day-tanzania-safari-express-tarangire-ngorongoro-crater/', slug: '2-day-express-tarangire-ngorongoro' },
  { title: '10 Days - Tarangire, Lake Manyara, Lake Natron, Serengeti, Ngorongoro Crater, and Lake Eyasi', price: 'From $4,500 USD*', special: false, grad: ['#7d3f20', '#2a1c12'], url: 'https://platoon-tours.com/10-days-tarangire-lake-manyara-lake-natron-serengeti-ngorongoro-crater-and-lake-eyasi/', slug: '10-days-tarangire-lake-manyara-lake-natron-serengeti-ngorongoro-crater-and-lake-eyasi' },
  { title: '5 Days - Lake Manyara, Ngorongoro Crater, Serengeti (2 nights), and Tarangire', price: 'From $1,900 USD*', special: false, grad: ['#3a5a6e', '#12242c'], url: 'https://platoon-tours.com/5-days-lake-manyara-ngorongoro-crater-serengeti-2-nights-and-tarangire/', slug: '5-days-lake-manyara-ngorongoro-crater-serengeti-2-nights-and-tarangire' },
  { title: '6 Days - Tarangire, Serengeti and Ngorongoro Crater', price: 'From $1,800 USD*', special: false, grad: ['#3d5c42', '#12201a'], url: 'https://platoon-tours.com/6-days-tarangire-serengeti-and-ngorongoro-crater/', slug: '6-days-tarangire-serengeti-and-ngorongoro-crater' },
];

export default safariPackages;
